### ISSUE TITLE
Fork for linux

### ISSUE THREAD

**Issue by dmansurov83** [DanPristupov/git-fork.com#1]
Hello! I know that this question is not about this repository.
I admire fork for windows and I really miss it on linux. Is there any way to make a build for debian?

**Comment by DanPristupov** [comment]
Hi. You probably wanted to find Fork issue tracker. It's located here: https://github.com/ForkIssues.

And here's the question about Linux: https://github.com/ForkIssues/Tracker/issues/153.

In short: Fork is native on both Mac and Windows and there's no way to *build* it on Linux.
